version: '3.8'

services:
  argus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
      - "8001:8001"
      - "5173:5173"
    environment:
      - SANDBOX_URL=http://localhost:8001
      - SERVICE=all
    env_file:
      - .env
